DELETE http://localhost:8080/employees/3

###

GET http://localhost:8080/employees
Accept: application/json

<> 2022-05-23T143655.200.json

###

PUT http://localhost:8080/employees/2
Content-Type: application/json

{
  "name": "Carlos",
  "role": "barman"
}

<> 2022-05-23T143640.200.json

###

POST http://localhost:8080/employees
Content-Type: application/json

{
  "name": "Ivan",
  "role": "admin"
}

<> 2022-05-23T143131.200.json

###

GET http://localhost:8080/employees
Accept: application/json

<> 2022-05-23T143109.200.json

###

POST http://localhost:8080/employees
Content-Type: application/json

{
  "name": "Pedro",
  "role": "admin"
}

<> 2022-05-23T143101.200.json

###

GET http://localhost:8080/employees/1
Accept: application/json

<> 2022-05-23T143051.200.json

###

GET https://localhost:8080/employees/1
Accept: application/json

###

GET http://localhost:8080/employees
Accept: application/json

<> 2022-05-23T143025.200.json

###

GET https://localhost:8080/employees
Accept: application/json

###

