openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
tags:
  - name: Employees
paths:
  /employees:
    post:
      tags:
        - Employees
      summary: Create employee
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEmployeeRequest'
      responses:
        201:
          description: New employee created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeResponse'
    get:
      tags:
        - Employees
      summary: Get all employees
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeesResponse'
components:
  schemas:
    CreateEmployeeRequest:
      title: CreateEmployeeResponse
      required:
        - employeename
        - role
      type: object
      properties:
        employeename:
          type: string
          description: Employees's employeename
          example: Juan
        role:
          type: string
          description: Employee's role
          example: admin
    EmployeeResponse:
      title: EmployeeResponse
      required:
        - id
        - employeename
      type: object
      properties:
        id:
          type: string
          description: Employees's identifier
          example: "1"
        employeename:
          type: string
          description: Employees's employeename
          example: Pedro
    EmployeesResponse:
      title: EmployeesResponse
      type: array
      items:
        type: object
        properties:
          id:
            type: string
            description: Employees's identifier
            example: "1"
          employeename:
            type: string
            description: Employees's employeename
            example: Pedro
          role:
            type: string
            description: Employees's role
            example: admin


